# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='<noname>', max_length=200),
        ),
    ]
