# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='hide_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='hide_name',
            field=models.BooleanField(default=False),
        ),
    ]
