---
# Deploy whole EventsMonkey app

- hosts: all
  gather_facts: False
  tasks:
    - raw: apt-get install python-minimal -y
  tags:
    - always

- hosts: all
  roles:
  - role: nginx
  - role: cvmortal
